name: DiskHound

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Compile
        run: python3 -m py_compile diskhound/diskhound.py
      - name: Test
        run: python3 -m unittest discover -s diskhound/tests -v
